In [ ]:
impor
t numpy as np

In [3]:
my_list = [1,2,3,4]
print(type(my_list))

<class 'list'>


In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [5]:
arr.shape

(4,)

In [6]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
arr.shape

(4,)

In [8]:
arr=arr.reshape(2,2)

In [9]:
arr.shape

(2, 2)

In [10]:
arr2 = np.array([1,2,3,4,5,6])

In [11]:
arr2.reshape(2,3)#2 is rows and 3 is columns

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.sum()

np.int64(21)

In [13]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ranges = np.arange(10)
ranges

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ranges=ranges.reshape(2,5)
ranges

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
lspace = np.linspace(1,10,2)
lspace

array([ 1., 10.])

In [21]:
lspace = np.linspace(1,10,5)
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
identity=np.identity(2)
identity

array([[1., 0.],
       [0., 1.]])

In [23]:
identity=np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
identity.shape

(5, 5)

In [25]:
ar=np.arange(99)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
ar.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
ar = ar.ravel()
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
x=[[1,2,3],[4,5,6],[7,1,0]]
new = np.array(x)
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
new.sum(axis=0)#it adds three columns

array([12,  8,  9])

In [30]:
new.sum(axis=1)#it adds rows of multiple arrays

array([ 6, 15,  8])

In [31]:
for i in new.flat:
    print(i)
    

1
2
3
4
5
6
7
1
0


In [32]:
new.ndim

2

In [33]:
new.size

9

In [34]:
one = np.array([1,2,3,4,5,6])

In [35]:
one.argmax()#it prints greatest number index it starts with 0

np.int64(5)

In [36]:
one=one.reshape(2,3)
one

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
one.argmin(axis=1)

array([0, 0])

In [38]:
one.argmax(axis=1)

array([2, 2])

In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[9,7],[4,6]])
a+b

array([[10,  9],
       [ 7, 10]])

In [43]:
a+b

array([[10,  9],
       [ 7, 10]])

In [44]:
a-b

array([[-8, -5],
       [-1, -2]])

In [45]:
a*b

array([[ 9, 14],
       [12, 24]])

In [46]:
a.sum() #it adds all values present in the array

np.int64(10)

In [47]:
a.max()#for maximum value

np.int64(4)

In [49]:
a.min()#for min value

np.int64(1)

In [ ]:
np.count_nonzero(a) # it counts non zero elements

np.int64(4)

In [51]:
my_list

[1, 2, 3, 4]

In [52]:
ary=np.array(my_list) #converts list into array

In [53]:
ary.tolist() # converts an array into list

[1, 2, 3, 4]

In [ ]:
ary.mean() #to get mean of the array

np.float64(2.5)